#!/usr/bin/env bash

docker push autochthe/kismet.base

docker push autochthe/kismet
docker push autochthe/kismet.discord
docker push autochthe/kismet.jupyter
docker push autochthe/kismet.jupyter.vim
