version: '3.5'
services:
  kismet.base:
    build:
      context: ..
      dockerfile: docker/kismet.base.dockerfile
    image: autochthe/kismet.base

  kismet:
    build:
      context: ..
      dockerfile: docker/kismet.dockerfile
    image: autochthe/kismet
    depends_on:
      - kismet.base

  kismet.discord:
    build:
      context: ..
      dockerfile: docker/kismet.discord.dockerfile
    image: autochthe/kismet.discord
    depends_on:
      - kismet

  kismet.slack:
    build:
      context: ..
      dockerfile: docker/kismet.slack.dockerfile
    image: autochthe/kismet.slack
    depends_on:
      - kismet

  kismet.jupyter:
    build:
      context: ..
      dockerfile: docker/kismet.jupyter.dockerfile
    image: autochthe/kismet.jupyter
    depends_on:
      - kismet
