apiVersion: v1
kind: Secret
metadata:
  name: kismet-secret
data:
  discord_clientid: {{ .Values.discord_clientid | toString | b64enc }}
  discord_token: {{ .Values.discord_token | toString | b64enc }}