apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}--discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}--discord
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}--discord
    spec:
      containers:
        - name: {{ .Chart.Name }}--discord
          image: autochthe/kismet.discord
          env:
            - name: DISCORD_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: kismet-secret
                  key: discord_clientid
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kismet-secret
                  key: discord_token
